### ISSUE TITLE
Generation doesn't seem to work with every .bib file as input

### ISSUE THREAD

**Issue by GabinL21** [Ducasse/Citezen#25]
Tried to generate an HTML file from this .bib:
```
@inproceedings{Anqu20a,
	author = {Nicolas Anquetil and Anne Etien and Houekpetodji, Mahugnon Honor\'e and Benoit Verhaeghe St\'ephane Ducasse and Clotilde Toullec and Fatija Djareddir and J\`erome Sudich and Mustapha Derras},
	title = {Modular Moose:  A new generation of software reengineering platform},
	booktitle = {International Conference on Software and Systems Reuse, ICSR2020},
	year = {2020},
	annote = {internationalconference},
	keywords = {kzEvolution},
	month = dec
}
```

Tried in Pharo 8 with this script:
```
bibset := CZBibParser parse: (FileStream readOnlyFileNamed: 'file.bib') contents.
bibset scope: CZSet standardDefinitions.
visitor := CZHTMLGenerator new filename: 'file.html'.
visitor visit: bibset.
```

And in Pharo 10 with this script:
```
bibset := CZBibParser parse: ('file.bib' asFileReference) contents.
bibset scope: CZSet standardDefinitions.
visitor := CZHTMLGenerator new filename: 'file.html'.
visitor visit: bibset.
```

None of them work, nothing is written in the HTML file.
But when trying to convert [this bib](https://github.com/UnivLille-Meta/Miage22/blob/main/Project-Citezen/rmod.bib) to HTML, it works perfectly.

Everything is fine until it has to write in the file. 
Other than that, the .bib is properly parsed, and Citezen manages to generate the HTML code.

Same issue with other generators (CZBblGenerator, CZBibTexGenerator, and CZLaTeXGenerator).

This workaround works in Pharo 10:
```
bibset := CZBibParser parse: ('file.bib' asFileReference) contents.
bibset scope: CZSet standardDefinitions.
result := (CZHTMLGenerator new visit: bibset) contents.
'file.html' asFileReference writeStreamDo: [ :stream | stream truncate. stream << result ].
```

**Comment by Ducasse** [comment]
Thanks for the information. Now may be the stream is not flushed or closed and writeStreamDo: does it while.
Can you check with a simple close. 
I use it often because http://stephane.ducasse.free.fr/Publications.html is generated from Citezen but I do not remember what I used. May be this is in the package Citezen-Stef
